runtime: python313
service: default

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.6

env_variables:
  # These will be set in Google Cloud Console
  GOOGLE_API_KEY: "your_gemini_api_key"
  GOOGLE_CLOUD_PROJECT: "your_project_id"
  DEBUG: "false"

handlers:
  # Serve the React build files
  - url: /static
    static_dir: frontend/build/static
    secure: always

  - url: /favicon.ico
    static_files: frontend/build/favicon.ico
    upload: frontend/build/favicon.ico
    secure: always

  # API routes
  - url: /api/.*
    script: auto
    secure: always

  - url: /health
    script: auto
    secure: always

  # Serve React app for all other routes
  - url: /.*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    secure: always